apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teste-completo
  namespace: teste-completo
  labels:
    app: teste-completo
    managed-by: backstage
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: teste-completo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: teste-completo
            port:
              number: 80
