apiVersion: v1
kind: Service
metadata:
  name: teste-completo
  namespace: teste-completo
  labels:
    app: teste-completo
    managed-by: backstage
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: teste-completo
